server:
  port: 8080

spring:
  application:
    name: retry
  datasource:
    name: retryDatasource
    username: root
    password: '!@#$1234Abcd'
    url: jdbc:mysql://127.0.0.1:3306/spring_boot_mq?useSSL=false&allowMultiQueries=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      pool-name: hikari-pool
      connection-timeout: 3000
      connection-test-query: select 1
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        ## \u5E76\u53D1\u8BBE\u7F6E
        concurrency: 5
        max-concurrency: 10
        prefetch: 3
        ## \u6D88\u8D39\u8005\u91CD\u8BD5
        retry:
          enabled: true
          max-attempts: 2
          initial-interval: 1000ms
          max-interval: 10000ms
        ## \u786E\u8BA4\u65B9\u5F0F
        acknowledge-mode: auto

mybatis:
  mapper-locations: classpath*:mapper/*.xml